apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  type: NodePort
  selector:
    app: expense-tracker-kubernative-project
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400